server:
  port: 8280

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true


  resources:
   static-locations: classpath:/webapp/WEB-INF

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  #type: com.alibaba.druid.pool.DruidDatasource


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zwx.basedata.entity
  #开启驼峰命名
  configuration:
   map-underscore-to-camel-case: true
   #开启缓存
   cache-enabled: true
   #开启自动生成id
   use-generated-keys: true

# 在控制台上打印sql (level后面的是包名)
logging:
  level:
    com:
      zwx:
        basedata:
          mapper: debug