
  #在Spring Boot中多环境配置文件名需要满足application-{profile}.yml的格式，
  #其中{profile}对应你的环境标识，比如：
  #application-dev.yml：开发环境
  #application-test.yml：测试环境
  #application-prod.yml：生产环境
  #至于哪个具体的配置文件会被加载，需要在application.yml文件中通过
  #spring.profiles.active属性来设置，其值对应{profile}值。

spring:
  profiles:
    active: dev